#!/usr/bin/env dash

# Locally install the focus tracker tool.
# This script will create a Python virtual environment in .venv .

# BACKEND SETUP
cd backend 
touch src/program.py
python3 -m venv .venv
# source the activate script to enter the venv and install necessary packages
# venv must be sourced as per the venv PyDoc guide: https://docs.python.org/3/library/venv.html#how-venvs-work
. .venv/bin/activate
pip3 install -r requirements.txt
deactivate
cd ..

# FRONTEND SETUP
cd frontend
npm install
