#!/bin/sh

# Locally install the focus tracker tool.
# This script will create a Python virtual environment in .venv .

# BACKEND SETUP
cd backend 
./setup
cd ..

# FRONTEND SETUP
cd frontend
[ -d node_modules ] && rm -r node_modules
npm install
