#!/bin/zsh

# usage: cov [ -[e]xecute tests ]

# tests not involving execute
pytest \
    --cov=src \
    --ignore=tests/execute \
    --cov-report=html \
    --cov-branch \
    --cov-config=.coveragerc # specify in here to remove src/execute.py from coverage

if ! [ "$1" = '-e' ] 
then
    exit 0
fi

banner() {
    python3 -c "print('-' * $(tput cols))"
}

colour() {
    # aqua
    printf '\033[1;36m'
}

reset() {
    printf '\033[0m'
}


echo ''
colour
banner
echo ''
echo 'hello!'
echo ''
banner
reset
echo ''
