#!/bin/zsh

# usage: cov [ -[e]xecute tests ]

# tests not involving execute
pytest \
    --cov=src \
    --ignore=tests/execute \
    --cov-report=html \
    --cov-branch \
    --cov-config=.coveragerc # specify in here to remove src/execute.py from coverage

[ "$1" = '-e' ] && ./test-execute
exit 0
