#!/bin/zsh

pytest \
    tests/function_calls \
    --cov=src \
    --ignore=tests/execute \
    --cov-report=html \
    --cov-branch \
    --cov-config=.coveragerc # specify in here to remove src/execute.py from coverage
