#!/bin/sh

# Locally install the focus tracker tool.
# This script will create a Python virtual environment in .venv .

[ -f src/program.py ] && rm src/program.py
touch src/program.py
[ -d .venv ] && rm -r .venv
python3 -m venv .venv
# source the activate script to enter the venv and install necessary packages
# venv must be sourced as per the venv PyDoc guide: https://docs.python.org/3/library/venv.html#how-venvs-work
. .venv/bin/activate
pip3 install -r requirements.txt
deactivate
