#!/bin/sh

# usage: start [ [-d]ebug ]

# in debug mode the server restarts itself when local changes are made
# this script does not need to be sourced even though the venv does

# get flask port configuration
. ./config.env

. .venv/bin/activate

if [ "$IN_DOCKER" = yes ]
then
    if [ "$1" = '-d' ]
    then
        flask --app server run -h 0.0.0.0 --debug
    else
        flask --app server run -h 0.0.0.0 
    fi
else
    if [ "$1" = '-d' ]
    then
        flask --app server run --debug
    else
        flask --app server run
    fi
fi

deactivate
