#!/bin/zsh

# usage: start [ [-d]ebug ]

# in debug mode the server restarts itself when local changes are made
# this script does not need to be sourced even though the venv does

. .venv/bin/activate

if [ "$1" = '-d' ]
then
    flask --app server run --debug
else
    flask --app server run
fi

# the subshell this script creates will automatically deactivate the virtual
# environment at the end
