#!/bin/zsh

# usage: start [ [-d]ebug ]

# in debug mode the server restarts itself when local changes are made

. .venv/bin/activate

if [ "$1" = '-d' ]
then
    flask --app server run
else
    flask --app server run --debug
fi
