#!/bin/sh

# find all common prefix names in test cases

prefixes () {
    find ../tests \
        -name '*.py' ! -name '__init__.py' \
        -exec basename {} \; | grep -E -o 'test_[a-z]+_' | sort | uniq
}

prefixes | while read prefix
do
    echo "prefix : $prefix"
    find ../tests -name "${prefix}*.py" | sed -E 's/^/    /'
done
